
//OpenGL bible sec 3 - tessellation evaluation shader

#version 450 core

//equal spacing along the tesselated polygon edges.  clockwise winding order
layout (triangles, equal_spacing, cw) in;

//runs an invocation for each vertex produced by the tesselator engine (after tesselation control stage)
//Want this to be simple if tesselation level is high

//gl_TessCoord is the barycentric coordinated of the vertex generated by the tesselator engine


 void main(void)
{
    gl_Position = (gl_TessCoord.x * gl_in[0].gl_Position +
                   gl_TessCoord.y * gl_in[1].gl_Position +
                   gl_TessCoord.z * gl_in[2].gl_Position);
}

//sb7 listing 3.8

